module.exports = {
  ...require("./AuthPayload"),
  ...require("./Mutation"),
  ...require("./Organizations"),
  ...require("./Query"),
  ...require("./User"),
  ...require("./CoursePage"),
  ...require("./Lesson"),
  ...require("./Application"),
  ...require("./Exercises"),
  ...require("./Results"),
  ...require("./NextType"),
  ...require("./Order"),
  ...require("./Enums"),
  ...require("./Post"),
};
